### PR TITLE
psr standard php

### PR DESCRIPTION
**Pull request by webbaard**
Change a bit of code, the way it was looked nothing like decent professional code. It's still not the best but it's a lot better now and think close the the max that can be put on a card. and the prevous code didn't even make sense. $this->$rank?

### CODE REVIEW

**Comment by mrlilly** [comment]
Bracket needs to be on new line for class declaration for PSR

**Comment by mrlilly** [comment]
On another note, the card method never gets called!

**Comment by webbaard** [comment]
Not sure about the need of calling the card? the Object is made. Would love to do doc blocks and constants but there's limited room.

**Comment by webbaard** [comment]
change function Code to __construct so it is supported in versions after 5.3

**Comment by Bathlamos** [comment]
I love your enthusiasm! The code is unfortunately too long to fit on the card. You need a maximum of 24 letters per row, and 8 rows. Can it be shrunk?

**Comment by mrlilly** [comment]
I do not think a clean OOP php snippet will be possible in the 8 lines. Maybe something simpler like this would have to be considered:

``` php
<?php
function card(
    $rank,
    $suit
) {
    return $rank . " of " . $suit;
}
echo card(6, "clubs");
```

Line 6 maybe too long though!

**Comment by mrlilly** [comment]
[6 - PHP.php.txt](https://github.com/Bathlamos/Programmers-Playing-Cards/files/336484/6.-.PHP.php.txt)

**Comment by Bathlamos** [comment]
Would something like this be good? I removed the <?php line and merged the "$rank" and "$suit" lines. We have a spare line, if needed to add something back.

**Comment by mrlilly** [comment]
I suggest putting the $suit back on its own line to retain PSR-2 coding style to fill the spare line.

**Comment by Bathlamos** [comment]
Perfect! I just modified the file. Thank you for the suggestion :) I'll close this issue for now, but let me know if there are other changes to be made!

**Pull request closed without merging**
