### PR TITLE
Code Functionality 

### PR DESCRIPTION
**Pull request by kylesf**
Required changes if written code is desired to be functional. If you have any questions, let me know. I know your considering spacing and design but I also think the ability for the code to run as is is very important.

### CODE REVIEW

**Comment by Bathlamos** [comment]
The ability to run the code is definitely important. Can I ask why you added ... to the MATLAB file?

**Comment by kylesf** [comment]
New to github, didn't necessarily mean for all of these commits to be grouped. With the matlab additions, for aesthetics, I changed double quotes to single quotes. As for me at least, that is more common place when writing code in matlab. The second commit is for two reasons. Firstly, you can't continue code onto multiple lines without the "..." (like the backslash in python). Secondly, when you don't suppress the code everything is outputted. Its makes the display command "useless" or "redundant". It is common place to suppress all outputs except for you want to be displayed in the command window.

**Comment by Bathlamos** [comment]
Thank you for the explanation! I didn't know about the automatic display of variables and the line continuation, so your change is definitely very appreciated. Thank you!!

**Comment by kylesf** [comment]
No problem, saw that kick starter is over. What will be the easiest way to acquire a set of these cards now or in future? Thanks

**Comment by Bathlamos** [comment]
I'd prefer not to sell any decks while they are not finalized (just in case). What I can do is take down your email and let you know when we start selling the decks. 

Send me a private message via my website (http://legault.cc) or the Kickstarter with your email address!

Thank you again!

**Pull request merged**
