### PR TITLE
added object version of c sharp

### PR DESCRIPTION
**Pull request by webbaard**
make the c# card an object

### CODE REVIEW

**Comment by TannerS** [comment]
will this fit into the card?

**Comment by webbaard** [comment]
that is a very good guestion, if I know how many line have to go i can make it smaller but the quality of the code will be a lot worse.

**Comment by TheSpyder** [comment]
I think #14 does this better. The card space is fairly limited.

**Comment by Bathlamos** [comment]
#14 was merged already. The code can be a maximum of 8 lines and have a width of 24 characters. Thank you for this pull request!

**Pull request closed without merging**
