### PR TITLE
Updated HTML structure

### PR DESCRIPTION
**Pull request by kix2902**
I think this HTML structure fits better with the rest of the deck adding the suit name in a [cite tag](http://www.w3schools.com/tags/tag_cite.asp)

### CODE REVIEW

**Comment by Bathlamos** [comment]
I know that semantically speaking, the HTML card isn't too good. The figurecaption tag and the figure tag would also have been good candidates. 

Only concern is: will entry-level programmers recognize these special tags? What do you think?

**Comment by kix2902** [comment]
Technically it isn't one of the most used tags, but if we follow that rule the span tag isn't one of them ([source1](http://www.99lime.com/_bak/topics/you-only-need-10-tags/), [source2](https://computerservices.temple.edu/commonly-used-html-tags))

Your idea of the figcaption tag is better than mine, use it and don't worry about a difficult tag in a "language" with about two dozens of tags in total.

**Comment by Bathlamos** [comment]
That's weird, I always use a bunch of spans everywhere because they are display:inline.

The html with figurecaption would be something like this, which doesn't look like HTML to me, at a first glance

```
<figure class="card">
    <img src="/ace.png">
    <figurecaption>
        Ace
        <span>1</span>
    </figurecaption>
</figure>
```

**Comment by kix2902** [comment]
I though the same, but stats are there… maybe the span tag is the eleventh in that list

Your code looks good to me, but I think it can be more HTML-ish with this change
`<body>
    <figure class="card">
        
        <figurecaption> Ace of Diamonds </figurecaption>
    </figure>
</body>`

_PS: I think looks better if all the languages mention the suit of the card_

**Comment by Bathlamos** [comment]
You're right then. I have made the change to the file.

The body tags are a bit too much for everything to fit on the card, but I too the rest verbatim from your last message. 

Thank you!!

**Comment by kix2902** [comment]
Thanks to you for the project.

**Pull request closed without merging**
