### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by TannerS**
Fixed "from collections...." line since in Python, indention matters and also put a space before "card = Card("hearts", 6)" for readability.

### CODE REVIEW

**Comment by Bathlamos** [comment]
That's a very good point. The challenge is that it must fit on this card. I added your line break, and a space in the line numbers on the left, so that it looks like the import is simply line-wrapped. How does that look?

**Comment by kylesf** [comment]
I would recommend adding a backslash after the from collections line to allow for the code to be functional. It will allow the code to fit on the card still. Otherwise it will not run due to improper formatting.

**Comment by TannerS** [comment]
looks great!

**Comment by Bathlamos** [comment]
Awesome! Thank you guys, I also added the backslash in the file.

**Pull request merged**
